package it.reactive.torneoDemo;

public class Costanti {
    public static final String TORNEO_DAO_JDBC_STATEMENT = "TORNEO_DAO_JDBC_STATEMENT";
    public static final String TORNEO_DAO_JDBC_PREPAREDSTATEMENT = "TORNEO_DAO_JDBC_PREPAREDSTATEMENT";
    public static final String TORNEO_DAO_SPRING_JDBC_QUERY_PSC = "TORNEO_DAO_SPRING_JDBC_QUERY_PSC";
    public static final String TORNEO_DAO_SPRING_JDBC_QUERY = "TORNEO_DAO_SPRING_JDBC_QUERY";
    public static final String TORNEO_DAO_SPRING_JDBC_QUERY_FORBC_QUERY = "TORNEO_DAO_SPRING_JDBC_QUERY_FORBC_QUERY";
    public static final String TORNEO_DAO_SPRING_JPA_JPAREPOSITORY = "TORNEO_DAO_SPRING_JPA_JPAREPOSITORY";
    public static final String TORNEO_DAO_SPRING_JPA_ENTITY_MANAGER_QUERY = "TORNEO_DAO_SPRING_JPA_ENTITY_MANAGER_QUERY";
    public static final String TORNEO_DAO_SPRING_JPA_ENTITY_MANAGER_BASE = "TORNEO_DAO_SPRING_JPA_ENTITY_MANAGER_BASE";
}
