spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"

error-manager:
  enabled: true

  connectors:
  jdbcConfigurations:
  default:
  connectionPoolSize: 5
  timeout: 30000
  mocked: false
  items:
  GetCountriesJdbcConnector:
  uri: ${DATASOURCE_URL}
  driver-class-name: org.posgresql.Driver
  username: ${DATASOURCE_USER:MCRE0_MPAB0_APP}
  password: ${DATASOURCE_PWD:MCRE0_MPAB0_APP}

#### Security configuration
keycloak:
  enabled: false
  auth-server-url:
  resource:
  realm:
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  bearer-only: true
  autodetect-bearer-only: true
  token-store: cookie
  security-constraints:
    - auth-roles:
        - openid
      security-collections:
        - name: reserved
          patterns:
            - /*
