spring.application.name=playwithspringbatch

spring.datasource.url=jdbc:postgresql://localhost:5432/torneobatch
spring.datasource.username=postgres
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver

