spring.application.name=torneoDemo

spring.datasource.url=jdbc:postgresql://localhost:5432/torneo
spring.datasource.username=postgres
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver

spring.profiles.active=${IMPLEMENTAZIONE_DAO_TORNEO}

#PROFILI ATTIVABILI:

# TORNEO_DAO_JDBC_STATEMENT
# TORNEO_DAO_JDBC_PREPAREDSTATEMENT
# TORNEO_DAO_SPRING_JDBC_QUERY_PSC
# TORNEO_DAO_SPRING_JDBC_QUERY
# TORNEO_DAO_SPRING_JDBC_QUERY_FORBC_QUERY
# TORNEO_DAO_SPRING_JPA_JPAREPOSITORY
# TORNEO_DAO_SPRING_JPA_ENTITY_MANAGER_QUERY
# TORNEO_DAO_SPRING_JPA_ENTITY_MANAGER_BASE