spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"

error-manager:
  enabled: true

connectors:
  bearInternalConfigurations:
    items:
      CountryRestConnector:
        url: http://localhost:8080/country/{id}
        enabledTracing: true
        timeout: 5000
        mocked: false
        method: POST

  eventConfigurations:
    items:
      KafkaEventConnector:
        topic: ${KAFKA_TOPIC_DEMO}
        bootstrapServers: ${KAFKA_STRATEGIA_BROKERS}
        groupId: ${KAFKA_STRATEGIA_GROUPID}
        concurrency: 3
        security:
          protocol: ${KAFKA_STRATEGIA_SECURITY_PROTOCOL}
        sasl:
          kerberos:
            service:
              name: ${KAFKA_STRATEGIA_SERVICE_NAME:xx}
          jaas:
            config: "com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true keyTab=\"${KEYTAB_STRATEGIA_KERB_FILE_PATH}\" principal=\"${KEYTAB_STRATEGIA_KERB_USERNAME}@${KEYTAB_STRATEGIA_KERB_REALM_DOMAIN}\";"

error-handling:
  #enable exception logging
  enableExceptionLogging: true
  #if error logging enabled this enable stacktrace logging
  enableStacktraceLogging: true
  #enable event raising on exception
  enableExceptionEvent: false
  #enable exception message decoding
  enableExceptionDecoding: true
  #if exception decoding is enabled this enable the tracking of unknown error message
  enableUnknowExceptionMapping: true
  #this in a tag for unknown error message log
  unknowExceptionTag: UNKNOWN_ERROR_CODE

session-manager:
  mocked: false
  allow-guest-session: false
  endpoint: your session manager endpoint

################################################################################################################
# TRACING NOTES

tracing:
  enabled: false
  mocked: false


#### Security configuration
keycloak:
  enabled: false
  auth-server-url:
  resource:
  realm:
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  bearer-only: true
  autodetect-bearer-only: true
  token-store: cookie
  security-constraints:
    - auth-roles:
        - openid
      security-collections:
        - name: reserved
          patterns:
            - /*
