spring.application.name=playwithspringbatch
#spring.batch.job.name=SECONDOJOB

nomeperquery=LUIGI

spring.datasource.url=jdbc:postgresql://localhost:5432/playwithspringbatch
spring.datasource.username=postgres
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource-clienti.jdbcUrl=jdbc:postgresql://localhost:5432/clientispringbatch
spring.datasource-clienti.username=postgres
spring.datasource-clienti.password=example
spring.datasource-clienti.driver-class-name=org.postgresql.Driver

spring.datasource-applicativa.jdbcUrl=jdbc:postgresql://localhost:5432/clientispringbatch
spring.datasource-applicativa.username=postgres
spring.datasource-applicativa.password=example
spring.datasource-applicativa.driver-class-name=org.postgresql.Driver
